---
title: "Plots"
output: html_notebook
---

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(ggplot2)

load("data/v1.RData")
load("data/v2.RData")
load("data/v3.RData")
```

```{r}
tib = tibble(it = 0:2000, v1, v2, v3)
```

```{r, fig.height = 5, fig.width = 10}
p1 = tib %>%
  ggplot(aes(x = it, y = v1)) +
  geom_point() +
  xlab("") +
  ylab("") +
  ylim(-10, 10) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.margin = margin(0, 0.5, 0, 0, "cm")) +
  geom_hline(yintercept = 7.5, linetype = "dashed") +
  geom_hline(yintercept = -7.5, linetype = "dashed") +
  scale_x_continuous(expand = c(0, 0))
p1
```

```{r, fig.height = 5, fig.width = 10}
p2 = tib %>%
  ggplot(aes(x = it, y = v2)) +
  geom_point() +
  xlab("") +
  ylab("") +
  ylim(-10, 10) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.margin = margin(0, 0.5, 0, 0, "cm")) +
  geom_hline(yintercept = 7.5, linetype = "dashed") +
  geom_hline(yintercept = -7.5, linetype = "dashed") +
  scale_x_continuous(expand = c(0, 0))
p2
```

```{r, fig.height = 5, fig.width = 10}
p3 = tib %>%
  ggplot(aes(x = it, y = v3)) +
  geom_point() +
  xlab("") +
  ylab("") +
  ylim(-10, 10) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.margin = margin(0, 0.5, 0, 0, "cm")) +
  geom_hline(yintercept = 7.5, linetype = "dashed") +
  geom_hline(yintercept = -7.5, linetype = "dashed") +
  scale_x_continuous(expand = c(0, 0))
p3
```